### ISSUE TITLE
Dynamic Schema?

### ISSUE THREAD

**Issue by willbuilds** [heitorsilva/json_playground#1]
Hi!

First off, I've been looking to do something similar in an application I'm working on, and your solution is really intriguing and quite simple and elegant.

I was wondering if you had put any thought into the idea that the schema default could change dynamically within the app. For example, in your soltuion the schema default is currently defined via migration (default values on the schema column) and is therefore the same for all users of the app. In my requirement, a user of the application (not all users, just a sort of administrator) would be able to modify the schema for a class. This is because it's a multi-tenanted application where each tenant has different schema requirements. Can you think of any ways to make the default value of the schema somehow come from a dynamic source? Can assume the schema must be provided in a json format for now.

The approach I was thinking of would be that Vehicle could have an after_initialize callback, that would then access the current default schema from another model (I've called Manufacturer). When the manufacturer changes it's schema, all future vehicles will use that schema, but old records will still be valid.

To use your current analogy, 
```
Class Manufacturer
  store_accessor :vehicle_default_schema, :required, :attributes 
end

Class Vehicle
  belongs_to :manufacturer

  after_initialize do
    if manufacturer.present? && self.new_record?
      self.schema = manufacturer.vehicle_default_schema
    end
    set_default_values
  end
end
```

Thoughts?

**Comment by heitorsilva** [comment]
Hey @wmulligan87! How are you?

I'm not sure if I understood correctly.

The default values are actually defined via migration, look:
https://github.com/heitorsilva/json_playground/blob/master/db/migrate/20190107230035_create_vehicles.rb

if you create another migration changing the field in the future, the past records will not be affected.

is that what you're worried about?

also, if you need a more dynamic default schema value, I suggest that you create a default_schemas table, with 2 fields, the schema itself and one field to determine the tenant.

whenever you create your record, the tenant of the record would be used to go over the default_schemas table and inject the one you need.

if a user changes a value on the default_schemas table (either via GUI, query or migrations), only affects future records and not past ones.

did I get where you wanted?

@motine, do you have any other input here?

**Comment by motine** [comment]
Interesting use case.

Similar to Heitor, I would probably store the default schema in an additional table rather than in the default value of a field.

**Comment by willbuilds** [comment]
Hey Heitor,

Sorry I'll try to be clearer. Your current approach assumes the the schema is constant and only changes when the developers decide, and in that case all users would have the same schemas.

In my scenario, I want the schema to be something that can be changed inside the app, so a user could decide 'oh I want to capture this extra field for this model', update the schema (somehow) inside the app, and from that point onwards all new instances of the model will be able to capture that field.

Sorry I hope that makes more sense. I'm doing a prototype of it myself at the moment, so I'll let you know if I find a good solution.

**Comment by heitorsilva** [comment]
hey @wmulligan87,

I understood correctly from the beginning then.

Again, I suggest you storing a table of schemas, and you relate your schema to whatever you want (your criteria seems to be tenant / user). I know they will be changeable, but they need to start with a default value anyhow. And again, as soon as someone changes the default values in this table (via GUI, or query, or migration, or rails cli), any past records are not broken because the old schema will be stored in the Vehicle table at each record.

The magic happens when you link the instantiation of a Vehicle to this new table. The secret lies in the implementation of this link between instantiation and new schemas table. Got me?!

Do you have a different idea than mine? Are there details I still didn't get?

**Comment by heitorsilva** [comment]
I will close this issue due to lack of activity.
